sudo:
  required

services:
  - docker

language: java
before_install:
- chmod +x gradlew

after_success:
#  - docker login -u $D_USER -p $D_PASS
#  - export NAME=rabot9ga/carservice
#  - docker build -t $NAME .
#  - docker push $NAME


  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - echo $TAG
  - echo $TRAVIS_COMMIT
  - docker login -u $D_USER -p $D_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=rabot9ga/carservice
  - docker build -t $IMAGE_NAME:$TRAVIS_COMMIT .
  - docker tag $IMAGE_NAME:$TRAVIS_COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME